name: probitas_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  file_picker: ^4.1.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  flutter_native_splash: ^2.1.6
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  get_storage: ^2.0.3
  google_fonts: 2.3.1
  hooks_riverpod: ^1.0.3
  intl: ^0.17.0
  lottie: ^1.3.0
  overlay_support: ^1.2.1
  pretty_dio_logger: ^1.1.1
  pull_to_refresh: ^2.0.0
  readmore: ^2.1.0
  smooth_page_indicator: ^1.0.0+2
  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  color_dark: "#1A1A2A"
  image_dark: assets/images/splashdark.png
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsons/
    - assets/icons/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
